name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://testuser:testpass@postgres:5432/testdb
      JWT_SECRET: github-actions-secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Ensure uploads dir
        run: mkdir -p uploads

      - name: Install Postgres client (for pg_isready)
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h postgres -p 5432 -U testuser && break
            echo "Waiting for Postgres... ($i)"; sleep 1
          done

      - name: Create .env for app
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" > .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "NODE_ENV=${NODE_ENV}" >> .env

      - name: Prisma version
        run: npx prisma --version

      - name: Prisma generate
        run: npx prisma generate

      - name: Prisma migrate (deploy)
        run: npx prisma migrate deploy

      - name: Run tests with coverage
        run: npx vitest run --coverage --reporter=verbose

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/